const express=require("express")
const cors=require("cors")
const app=express()
const routes=require("./routes/index")
app.use(express.json())
app.use(cors())
app.use("/api",routes)
app.listen(3000,()=>console.log("started at port 3000"))